name: Acquire activation file
on: 
  workflow_dispatch:
    inputs:
      versionInput:
        description: 'Unity Version'     
        required: true
        default: '2021.1.1f1'
jobs:
  activation:
    name: Request manual activation file ??
    runs-on: ubuntu-latest
    steps:

    # Request manual activation file
    - name: Request manual activation file
      id: getManualLicenseFile
      uses: game-ci/unity-request-activation-file@v2
      with:
        unityVersion: ${{ github.event.inputs.versionInput }}

    # Upload artifact (Unity_v20XX.X.XXXX.alf)
    - name: Expose as artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}